const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

// Static historical context data for all 66 Bible books
const BOOK_CONTEXT: Record<string, {
  author: string;
  period: string;
  audience: string;
  setting: string;
  themes: string[];
  summary: string;
}> = {
  "Gênesis": {
    author: "Moisés (tradição)",
    period: "~1450–1400 a.C.",
    audience: "Israelitas no deserto",
    setting: "Da criação ao Egito — abrange milhares de anos",
    themes: ["Criação", "Queda", "Aliança", "Promessa", "Eleição"],
    summary: "Narra as origens do mundo e do povo de Deus, desde Adão até José no Egito.",
  },
  "Êxodo": {
    author: "Moisés",
    period: "~1450–1400 a.C.",
    audience: "Israelitas recém-libertos",
    setting: "Egito e deserto do Sinai",
    themes: ["Libertação", "Lei", "Tabernáculo", "Aliança", "Presença de Deus"],
    summary: "Deus liberta Israel da escravidão e estabelece sua aliança no Sinai.",
  },
  "Levítico": {
    author: "Moisés",
    period: "~1445 a.C.",
    audience: "Sacerdotes e povo de Israel",
    setting: "Monte Sinai",
    themes: ["Santidade", "Sacrifício", "Pureza", "Expiação"],
    summary: "Manual de adoração e santidade para o povo da aliança.",
  },
  "Números": {
    author: "Moisés",
    period: "~1400 a.C.",
    audience: "Segunda geração de Israel",
    setting: "Deserto entre Sinai e Canaã",
    themes: ["Peregrinação", "Fidelidade", "Murmuração", "Julgamento"],
    summary: "Os 40 anos de peregrinação no deserto, marcados por fé e rebeldia.",
  },
  "Deuteronômio": {
    author: "Moisés",
    period: "~1406 a.C.",
    audience: "Nova geração prestes a entrar em Canaã",
    setting: "Planícies de Moabe",
    themes: ["Renovação da aliança", "Obediência", "Bênção e maldição"],
    summary: "Discursos finais de Moisés renovando a aliança antes da conquista.",
  },
  "Josué": {
    author: "Josué (tradição)",
    period: "~1400–1370 a.C.",
    audience: "Israel conquistador",
    setting: "Terra de Canaã",
    themes: ["Conquista", "Fidelidade de Deus", "Herança", "Obediência"],
    summary: "A conquista e divisão da Terra Prometida sob a liderança de Josué.",
  },
  "Juízes": {
    author: "Desconhecido (possivelmente Samuel)",
    period: "~1370–1050 a.C.",
    audience: "Israel nos primeiros séculos em Canaã",
    setting: "Terra de Israel, período tribal",
    themes: ["Ciclo de pecado", "Juízes libertadores", "Anarquia", "Misericórdia"],
    summary: "Ciclos de apostasia, opressão, clamor e libertação por juízes.",
  },
  "Rute": {
    author: "Desconhecido",
    period: "Época dos juízes (~1100 a.C.)",
    audience: "Israel",
    setting: "Belém de Judá e Moabe",
    themes: ["Redenção", "Lealdade", "Providência", "Linhagem messiânica"],
    summary: "História de fidelidade e redenção na linhagem de Davi e do Messias.",
  },
  "1 Samuel": {
    author: "Samuel, Gade, Natã (tradição)",
    period: "~1050–1010 a.C.",
    audience: "Israel na transição para a monarquia",
    setting: "Israel, de Siló a Gibeá",
    themes: ["Monarquia", "Rejeição", "Unção", "Soberania de Deus"],
    summary: "Transição de juízes para reis: Samuel, Saul e a ascensão de Davi.",
  },
  "2 Samuel": {
    author: "Gade, Natã (tradição)",
    period: "~1010–970 a.C.",
    audience: "Israel unificado",
    setting: "Jerusalém e arredores",
    themes: ["Aliança davídica", "Pecado e consequências", "Graça"],
    summary: "O reinado de Davi, suas vitórias, pecados e a promessa messiânica.",
  },
  "1 Reis": {
    author: "Desconhecido (possivelmente Jeremias)",
    period: "~970–850 a.C.",
    audience: "Israel e Judá",
    setting: "Jerusalém e reinos divididos",
    themes: ["Sabedoria", "Templo", "Divisão", "Profecia"],
    summary: "Salomão, o templo, a divisão do reino e os primeiros profetas.",
  },
  "2 Reis": {
    author: "Desconhecido",
    period: "~850–586 a.C.",
    audience: "Exilados e remanescentes",
    setting: "Israel e Judá até o exílio",
    themes: ["Julgamento", "Exílio", "Profecia", "Arrependimento"],
    summary: "Declínio e queda dos dois reinos, culminando no exílio babilônico.",
  },
  "1 Crônicas": {
    author: "Esdras (tradição)",
    period: "Pós-exílio (~450 a.C.)",
    audience: "Comunidade pós-exílica",
    setting: "Retrospectiva: de Adão a Davi",
    themes: ["Adoração", "Templo", "Genealogia", "Aliança davídica"],
    summary: "Genealogias e o reinado de Davi com ênfase na adoração.",
  },
  "2 Crônicas": {
    author: "Esdras (tradição)",
    period: "Pós-exílio",
    audience: "Judeus retornados",
    setting: "De Salomão ao exílio",
    themes: ["Templo", "Reforma", "Fidelidade", "Oração"],
    summary: "Reis de Judá avaliados pela fidelidade ao templo e à aliança.",
  },
  "Esdras": {
    author: "Esdras",
    period: "~538–450 a.C.",
    audience: "Comunidade restaurada",
    setting: "Jerusalém pós-exílio",
    themes: ["Restauração", "Templo", "Lei", "Arrependimento"],
    summary: "Retorno do exílio e reconstrução do templo e da vida espiritual.",
  },
  "Neemias": {
    author: "Neemias",
    period: "~445–430 a.C.",
    audience: "Judeus em Jerusalém",
    setting: "Jerusalém, muros destruídos",
    themes: ["Reconstrução", "Liderança", "Oração", "Reforma"],
    summary: "Reconstrução dos muros de Jerusalém e renovação da aliança.",
  },
  "Ester": {
    author: "Desconhecido",
    period: "~486–465 a.C.",
    audience: "Judeus na diáspora persa",
    setting: "Susã, capital da Pérsia",
    themes: ["Providência", "Coragem", "Preservação", "Identidade"],
    summary: "Deus preserva seu povo por meio de Ester na corte persa.",
  },
  "Jó": {
    author: "Desconhecido",
    period: "Época patriarcal",
    audience: "Sábios de Israel",
    setting: "Terra de Uz",
    themes: ["Sofrimento", "Soberania de Deus", "Fé", "Sabedoria"],
    summary: "O sofrimento do justo e o encontro com o Deus soberano.",
  },
  "Salmos": {
    author: "Davi, Asafe, filhos de Corá e outros",
    period: "~1000–400 a.C.",
    audience: "Adoradores de Israel",
    setting: "Liturgia do templo e devoção pessoal",
    themes: ["Louvor", "Lamento", "Confiança", "Messias", "Criação"],
    summary: "Hinário de Israel expressando toda a gama de emoções humanas diante de Deus.",
  },
  "Provérbios": {
    author: "Salomão e outros sábios",
    period: "~950–700 a.C.",
    audience: "Jovens e sábios de Israel",
    setting: "Corte real e vida cotidiana",
    themes: ["Sabedoria", "Temor do Senhor", "Justiça", "Disciplina"],
    summary: "Instruções práticas para uma vida sábia segundo o temor do Senhor.",
  },
  "Eclesiastes": {
    author: "Salomão (tradição)",
    period: "~935 a.C.",
    audience: "Buscadores de significado",
    setting: "Reflexão filosófica em Jerusalém",
    themes: ["Vaidade", "Sentido da vida", "Temor de Deus", "Sabedoria"],
    summary: "Reflexão sobre o sentido da vida: tudo é vaidade sem Deus.",
  },
  "Cantares": {
    author: "Salomão",
    period: "~960 a.C.",
    audience: "Israel",
    setting: "Cenas pastorais e urbanas",
    themes: ["Amor", "Beleza", "União", "Aliança"],
    summary: "Poema do amor entre o amado e a amada, reflexo do amor de Deus.",
  },
  "Isaías": {
    author: "Isaías",
    period: "~740–680 a.C.",
    audience: "Judá e as nações",
    setting: "Jerusalém, ameaça assíria",
    themes: ["Julgamento", "Consolação", "Servo sofredor", "Novo êxodo"],
    summary: "Visão do Santo de Israel: julgamento presente e redenção futura.",
  },
  "Jeremias": {
    author: "Jeremias",
    period: "~627–586 a.C.",
    audience: "Judá pré-exílio",
    setting: "Jerusalém sob ameaça babilônica",
    themes: ["Arrependimento", "Nova aliança", "Julgamento", "Esperança"],
    summary: "O profeta chorão anuncia o juízo e a nova aliança.",
  },
  "Lamentações": {
    author: "Jeremias (tradição)",
    period: "~586 a.C.",
    audience: "Sobreviventes da destruição",
    setting: "Jerusalém destruída",
    themes: ["Lamento", "Juízo", "Fidelidade de Deus", "Esperança"],
    summary: "Lamentos pela destruição de Jerusalém, com fé na fidelidade de Deus.",
  },
  "Ezequiel": {
    author: "Ezequiel",
    period: "~593–571 a.C.",
    audience: "Exilados na Babilônia",
    setting: "Rio Quebar, Babilônia",
    themes: ["Glória de Deus", "Juízo", "Restauração", "Novo templo"],
    summary: "Visões da glória de Deus partindo e retornando ao templo restaurado.",
  },
  "Daniel": {
    author: "Daniel",
    period: "~605–535 a.C.",
    audience: "Judeus exilados",
    setting: "Cortes da Babilônia e Pérsia",
    themes: ["Soberania", "Reinos", "Fidelidade", "Profecia apocalíptica"],
    summary: "Deus reina sobre os impérios e revelará seu reino eterno.",
  },
  "Oséias": {
    author: "Oséias",
    period: "~755–715 a.C.",
    audience: "Reino do Norte (Israel)",
    setting: "Israel, antes da queda de Samaria",
    themes: ["Amor fiel", "Infidelidade", "Arrependimento", "Restauração"],
    summary: "O amor fiel de Deus por um povo infiel, ilustrado no casamento de Oséias.",
  },
  "Joel": {
    author: "Joel",
    period: "~835 a.C. (debatido)",
    audience: "Judá",
    setting: "Judá após uma praga de gafanhotos",
    themes: ["Dia do Senhor", "Arrependimento", "Espírito Santo"],
    summary: "Do juízo ao derramamento do Espírito — o Dia do Senhor.",
  },
  "Amós": {
    author: "Amós",
    period: "~760 a.C.",
    audience: "Reino do Norte (Israel)",
    setting: "Samaria, em época de prosperidade",
    themes: ["Justiça social", "Juízo", "Remanescente", "Dia do Senhor"],
    summary: "Pastor-profeta denuncia injustiça e anuncia juízo às nações.",
  },
  "Obadias": {
    author: "Obadias",
    period: "~586 a.C.",
    audience: "Edom e Judá",
    setting: "Pós-destruição de Jerusalém",
    themes: ["Juízo sobre Edom", "Soberania", "Restauração"],
    summary: "O menor livro profético: juízo contra Edom por trair seu irmão.",
  },
  "Jonas": {
    author: "Jonas",
    period: "~780 a.C.",
    audience: "Israel",
    setting: "Nínive, capital assíria",
    themes: ["Misericórdia", "Missão", "Arrependimento", "Soberania"],
    summary: "Deus estende misericórdia até aos inimigos de Israel.",
  },
  "Miquéias": {
    author: "Miquéias",
    period: "~735–700 a.C.",
    audience: "Judá e Samaria",
    setting: "Judá sob ameaça assíria",
    themes: ["Justiça", "Misericórdia", "Messias de Belém"],
    summary: "Juízo e esperança: de Belém virá o governante eterno.",
  },
  "Naum": {
    author: "Naum",
    period: "~663–612 a.C.",
    audience: "Judá",
    setting: "Queda iminente de Nínive",
    themes: ["Juízo divino", "Soberania", "Consolo para o oprimido"],
    summary: "Oráculo contra Nínive: Deus é justo e vingador.",
  },
  "Habacuque": {
    author: "Habacuque",
    period: "~608–598 a.C.",
    audience: "Judá",
    setting: "Ascensão da Babilônia",
    themes: ["Fé", "Justiça de Deus", "Soberania", "O justo viverá pela fé"],
    summary: "Diálogo com Deus sobre o mal: o justo viverá pela fé.",
  },
  "Sofonias": {
    author: "Sofonias",
    period: "~640–620 a.C.",
    audience: "Judá pré-reforma de Josias",
    setting: "Jerusalém, sincretismo religioso",
    themes: ["Dia do Senhor", "Juízo", "Remanescente humilde"],
    summary: "Juízo universal e esperança para um remanescente humilde.",
  },
  "Ageu": {
    author: "Ageu",
    period: "520 a.C.",
    audience: "Judeus retornados do exílio",
    setting: "Jerusalém, templo em ruínas",
    themes: ["Prioridades", "Templo", "Glória futura"],
    summary: "Chamado urgente para reconstruir o templo — a glória virá.",
  },
  "Zacarias": {
    author: "Zacarias",
    period: "~520–480 a.C.",
    audience: "Comunidade pós-exílica",
    setting: "Jerusalém em reconstrução",
    themes: ["Messias", "Restauração", "Visões apocalípticas", "Espírito"],
    summary: "Visões messiânicas ricas: o Rei humilde, o Pastor ferido, a fonte aberta.",
  },
  "Malaquias": {
    author: "Malaquias",
    period: "~460–430 a.C.",
    audience: "Judá pós-exílico",
    setting: "Jerusalém, templo reconstruído",
    themes: ["Fidelidade", "Dízimo", "Precursor do Messias", "Dia do Senhor"],
    summary: "Último profeta do AT: chamado à fidelidade antes do silêncio.",
  },
  "Mateus": {
    author: "Mateus (Levi)",
    period: "~55–65 d.C.",
    audience: "Judeus cristãos",
    setting: "Palestina, início da Igreja",
    themes: ["Reino dos céus", "Cumprimento profético", "Discipulado", "Lei"],
    summary: "Jesus é o Messias prometido que inaugura o Reino dos céus.",
  },
  "Marcos": {
    author: "João Marcos",
    period: "~55–65 d.C.",
    audience: "Cristãos romanos",
    setting: "Roma, sob perseguição",
    themes: ["Servo sofredor", "Ação", "Segredo messiânico", "Cruz"],
    summary: "O Servo de Deus em ação — o evangelho da urgência e da cruz.",
  },
  "Lucas": {
    author: "Lucas (médico)",
    period: "~60–62 d.C.",
    audience: "Teófilo e gentios",
    setting: "Investigação ordenada",
    themes: ["Salvação universal", "Espírito Santo", "Pobres", "Mulheres"],
    summary: "Jesus, Salvador de todos os povos, traz graça aos marginalizados.",
  },
  "João": {
    author: "João (apóstolo)",
    period: "~85–95 d.C.",
    audience: "Cristãos e buscadores",
    setting: "Éfeso (tradição)",
    themes: ["Divindade de Cristo", "Sinais", "Fé", "Vida eterna"],
    summary: "O Verbo se fez carne — crer em Jesus é ter vida eterna.",
  },
  "Atos": {
    author: "Lucas",
    period: "~62–64 d.C.",
    audience: "Teófilo e a Igreja",
    setting: "De Jerusalém até Roma",
    themes: ["Espírito Santo", "Missão", "Igreja", "Expansão do evangelho"],
    summary: "O Espírito impulsiona a Igreja de Jerusalém aos confins da terra.",
  },
  "Romanos": {
    author: "Paulo",
    period: "~57 d.C.",
    audience: "Igreja em Roma",
    setting: "Escrita de Corinto",
    themes: ["Justificação pela fé", "Graça", "Lei", "Israel", "Vida no Espírito"],
    summary: "A obra-prima teológica de Paulo: justificação pela fé para todos.",
  },
  "1 Coríntios": {
    author: "Paulo",
    period: "~55 d.C.",
    audience: "Igreja em Corinto",
    setting: "Cidade cosmopolita grega",
    themes: ["Unidade", "Santidade", "Dons espirituais", "Ressurreição"],
    summary: "Correções para uma igreja dividida: a cruz é sabedoria de Deus.",
  },
  "2 Coríntios": {
    author: "Paulo",
    period: "~56 d.C.",
    audience: "Igreja em Corinto",
    setting: "Escrita da Macedônia",
    themes: ["Ministério", "Fraqueza e poder", "Reconciliação", "Generosidade"],
    summary: "O poder de Deus se aperfeiçoa na fraqueza do apóstolo.",
  },
  "Gálatas": {
    author: "Paulo",
    period: "~49 d.C.",
    audience: "Igrejas da Galácia",
    setting: "Conflito sobre circuncisão",
    themes: ["Liberdade", "Justificação pela fé", "Espírito vs. carne"],
    summary: "Liberdade em Cristo: não voltem à escravidão da lei.",
  },
  "Efésios": {
    author: "Paulo",
    period: "~60–62 d.C.",
    audience: "Igreja em Éfeso e região",
    setting: "Prisão em Roma",
    themes: ["Igreja", "Unidade", "Graça", "Armadura de Deus"],
    summary: "O plano eterno de Deus: unir todas as coisas em Cristo.",
  },
  "Filipenses": {
    author: "Paulo",
    period: "~61 d.C.",
    audience: "Igreja em Filipos",
    setting: "Prisão em Roma",
    themes: ["Alegria", "Humildade de Cristo", "Cidadania celestial"],
    summary: "Alegria em Cristo mesmo nas cadeias — o hino kenótico.",
  },
  "Colossenses": {
    author: "Paulo",
    period: "~60–62 d.C.",
    audience: "Igreja em Colossos",
    setting: "Prisão em Roma",
    themes: ["Supremacia de Cristo", "Plenitude", "Heresia"],
    summary: "Cristo é supremo sobre tudo — nele habita toda plenitude.",
  },
  "1 Tessalonicenses": {
    author: "Paulo",
    period: "~51 d.C.",
    audience: "Igreja em Tessalônica",
    setting: "Escrita de Corinto",
    themes: ["Volta de Cristo", "Santificação", "Esperança"],
    summary: "Encorajamento para viver em santidade aguardando a volta de Cristo.",
  },
  "2 Tessalonicenses": {
    author: "Paulo",
    period: "~51 d.C.",
    audience: "Igreja em Tessalônica",
    setting: "Escrita de Corinto",
    themes: ["Dia do Senhor", "Anticristo", "Perseverança"],
    summary: "Correção sobre a volta de Cristo e exortação à firmeza.",
  },
  "1 Timóteo": {
    author: "Paulo",
    period: "~64 d.C.",
    audience: "Timóteo em Éfeso",
    setting: "Pastoreio de igreja local",
    themes: ["Liderança", "Sã doutrina", "Piedade", "Ordem na igreja"],
    summary: "Manual pastoral para Timóteo: guardar a sã doutrina.",
  },
  "2 Timóteo": {
    author: "Paulo",
    period: "~67 d.C.",
    audience: "Timóteo",
    setting: "Última prisão de Paulo em Roma",
    themes: ["Perseverança", "Palavra de Deus", "Sofrimento", "Legado"],
    summary: "Testamento final de Paulo: combati o bom combate.",
  },
  "Tito": {
    author: "Paulo",
    period: "~64 d.C.",
    audience: "Tito em Creta",
    setting: "Organização de igrejas em Creta",
    themes: ["Boas obras", "Liderança", "Graça", "Sã doutrina"],
    summary: "A graça de Deus instrui para uma vida piedosa e produtiva.",
  },
  "Filemom": {
    author: "Paulo",
    period: "~60–62 d.C.",
    audience: "Filemom",
    setting: "Prisão de Paulo em Roma",
    themes: ["Perdão", "Reconciliação", "Igualdade em Cristo"],
    summary: "Paulo intercede por Onésimo: em Cristo, escravo se torna irmão.",
  },
  "Hebreus": {
    author: "Desconhecido",
    period: "~64–68 d.C.",
    audience: "Cristãos judeus tentados a voltar ao judaísmo",
    setting: "Pré-destruição do templo",
    themes: ["Superioridade de Cristo", "Sacerdócio", "Fé", "Nova aliança"],
    summary: "Cristo é superior a tudo: anjos, Moisés, sacerdócio, sacrifícios.",
  },
  "Tiago": {
    author: "Tiago (irmão de Jesus)",
    period: "~45–49 d.C.",
    audience: "Judeus cristãos dispersos",
    setting: "Jerusalém primitiva",
    themes: ["Fé e obras", "Sabedoria prática", "Língua", "Provações"],
    summary: "Fé sem obras é morta — sabedoria prática para a vida cristã.",
  },
  "1 Pedro": {
    author: "Pedro",
    period: "~63–64 d.C.",
    audience: "Cristãos perseguidos na Ásia Menor",
    setting: "Roma (Babilônia)",
    themes: ["Sofrimento", "Esperança viva", "Santidade", "Submissão"],
    summary: "Esperança viva em meio ao sofrimento — pedras vivas.",
  },
  "2 Pedro": {
    author: "Pedro",
    period: "~66–68 d.C.",
    audience: "Cristãos ameaçados por falsos mestres",
    setting: "Pouco antes da morte de Pedro",
    themes: ["Falsos mestres", "Dia do Senhor", "Crescimento na graça"],
    summary: "Alerta contra falsos mestres e exortação ao crescimento.",
  },
  "1 João": {
    author: "João (apóstolo)",
    period: "~85–95 d.C.",
    audience: "Igrejas da Ásia Menor",
    setting: "Éfeso, conflito com proto-gnosticismo",
    themes: ["Luz", "Amor", "Verdade", "Certeza da salvação"],
    summary: "Deus é luz e amor — como sabemos que temos vida eterna.",
  },
  "2 João": {
    author: "João",
    period: "~85–95 d.C.",
    audience: "Senhora eleita (igreja local)",
    setting: "Éfeso",
    themes: ["Verdade", "Amor", "Discernimento"],
    summary: "Andar em verdade e amor, rejeitando falsos mestres.",
  },
  "3 João": {
    author: "João",
    period: "~85–95 d.C.",
    audience: "Gaio",
    setting: "Éfeso",
    themes: ["Hospitalidade", "Verdade", "Liderança servil"],
    summary: "Elogio à hospitalidade de Gaio e repreensão a Diótrefes.",
  },
  "Judas": {
    author: "Judas (irmão de Jesus)",
    period: "~65–80 d.C.",
    audience: "Cristãos ameaçados",
    setting: "Infiltração de falsos mestres",
    themes: ["Contender pela fé", "Juízo", "Falsos mestres"],
    summary: "Batalhar pela fé entregue aos santos contra falsos mestres.",
  },
  "Apocalipse": {
    author: "João (apóstolo)",
    period: "~95 d.C.",
    audience: "Sete igrejas da Ásia",
    setting: "Ilha de Patmos, perseguição romana",
    themes: ["Vitória de Cristo", "Juízo", "Nova criação", "Adoração"],
    summary: "A revelação de Jesus Cristo: do sofrimento presente à glória eterna.",
  },
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { book } = await req.json();

    const ctx = BOOK_CONTEXT[book];

    if (!ctx) {
      return new Response(
        JSON.stringify({
          author: "Desconhecido",
          period: "—",
          audience: "Povo de Deus",
          setting: "Antigo Oriente Próximo",
          themes: ["Revelação", "Aliança"],
          summary: `Contexto detalhado para ${book} ainda não disponível.`,
        }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    return new Response(JSON.stringify(ctx), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    return new Response(
      JSON.stringify({ error: (error as Error).message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
